title: FATE in the BAWG
description: A website to track the progress of our FATE game in the BAWG
theme: just-the-docs

url: https://jackdesmarais.github.io/FATE_in_the_BAWG/

aux_links:
  Template Repository: https://github.com/jackdesmarais/FATE_in_the_BAWG

collections_dir: my_collections

collections:
  - name: "Locations"
    output: true
