title: FATE in the BAWG
description: A website to track the progress of our FATE game in the BAWG
theme: just-the-docs

url: https://jackdesmarais.github.io/FATE_in_the_BAWG/

aux_links:
  Template Repository: https://github.com/jackdesmarais/FATE_in_the_BAWG

favicon_ico: "/gem-stone-emoji-clipart-lg.png"

collections:
  creatures:
    permalink: "/:collection/:path.html"
    output: true
  factions:
    permalink: "/:collection/:path.html"
    output: true
  locations:
    permalink: "/:collection/:path.html"
    output: true
  NPCs:
    permalink: "/:collection/:path.html"
    output: true
  PCs:
    permalink: "/:collection/:path.html"
    output: true
  session_notes:
    permalink: "/:collection/:path.html"
    output: true
  subsystems:
    permalink: "/:collection/:path.html"
    output: true
  spiritual_realms:
    permalink: "/:collection/:path.html"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    creatures:
      name: Creatures
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    factions:
      name: Factions
      nav_exclude: False
      nav_fold: true
      search_exclude: false
    locations:
      name: Locations
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    NPCs:
      name: NPCs
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    PCs:
      name: PCs
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    session_notes:
      name: Session Notes
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    subsystems:
      name: Subsystems
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    spiritual_realms:
      name: Spiritual Realms
      nav_exclude: false
      nav_fold: true
      search_exclude: false

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page."
gh_edit_repository: "https://github.com/jackdesmarais/FATE_in_the_BAWG" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
