title: JTD_TEST_2
description: A test site for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://jackdesmarais.github.io/JTD_TEST_2

aux_links:
  Template Repository: https://github.com/jackdesmarais/JTD_TEST_2
